### ISSUE TITLE
Clokta incorrectly expecting `?fromHome=true` at end of copy-and-pasted Okta tile urls

### ISSUE THREAD

**Issue by hs4man21** [washingtonpost/clokta#22]
Clokta has a minor issue where it expects `?fromHome=true` at the end of any Okta url that is copied from Guidepost and pasted in to the terminal set up a profile. Is there a reason for this? I've had to append `?fromHome=true` to copied Okta tile urls manually a couple times recently to get things working.

**Comment by rantonucci-washpost** [comment]
Fixed in clokta 4.1.3.
