### ISSUE TITLE
Unable to register a profile if the AWS_PROFILE is set with the name profile

### ISSUE THREAD

**Issue by FelipeRuizGarcia** [washingtonpost/clokta#23]
1. set the env variable AWS_PROFILE like test

``` 
export  AWS_PROFILE=test
```

2. Create the clokta profile
```
clokta -p test
```

3. Save and you willl see the botocore error for 
```
ProfileNotFound
```

Also, you can try deleting the ~/.aws  and ~/.clokta directories

**Comment by rantonucci-washpost** [comment]
Fixed in clokta 4.1.3
